### ISSUE TITLE
processing raw data to input data

### ISSUE THREAD

**Issue by qiuxia-alone** [butyr/huggingface-dialogpt-finetuning#1]
hi, is single input data like `[sentence_1_token_ids, eos_token_id, sentence_2_token_ids, eos_token_id, ……, sentence_n_token_ids, eos_token_id]`after processing?

**Comment by butyr** [comment]
Hi, 
so I finally came around to take a look at the HF documentation and the original paper. You are right in so far as the padding actually needs to be explicitly added to the tokenizer. Then there is no need to explicitly pad everything using pad_sequence, since the tokenizer can take care of the padding. I will add this change some time soon. 

Positional ids are computed automatically if not provided, and GPT-type transformers don't use token_type_ids. If I am not mistaken, the token_type_ids are more a BERT thing. 

It is very possible though, that I do need to shift the inputs by one turn, when I am using them as the labels. I had a translation perspective in mind. I will have to take a look in how HF handles the inputs there.
